"""create leave payroll notifications and audit logs

Revision ID: 2f6b7418ebe9
Revises: d30018a7321b
Create Date: 2026-08-22 13:53:03.482212
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "2f6b7418ebe9"
down_revision: str | None = "d30018a7321b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_logs",
        sa.Column("actor_id", sa.Uuid(), nullable=True),
        sa.Column("action", sa.String(length=100), nullable=False),
        sa.Column("entity_type", sa.String(length=100), nullable=False),
        sa.Column("entity_id", sa.String(length=100), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["actor_id"],
            ["users.id"],
            name=op.f("fk_audit_logs_actor_id_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_logs")),
    )
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_audit_logs_action"), ["action"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_actor_id"), ["actor_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_created_at"), ["created_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_audit_logs_entity_id"), ["entity_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_audit_logs_entity_type"), ["entity_type"], unique=False
        )

    op.create_table(
        "leave_requests",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column(
            "leave_type",
            sa.Enum("PAID", "SICK", "UNPAID", name="leavetype", native_enum=False, length=16),
            nullable=False,
        ),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("number_of_days", sa.Integer(), nullable=False),
        sa.Column("reason", sa.Text(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "APPROVED",
                "REJECTED",
                "CANCELLED",
                name="leavestatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("employee_remarks", sa.String(length=1000), nullable=True),
        sa.Column("reviewer_comment", sa.String(length=1000), nullable=True),
        sa.Column("reviewed_by", sa.Uuid(), nullable=True),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "leave_type IN ('PAID', 'SICK', 'UNPAID')", name=op.f("ck_leave_requests_leave_type")
        ),
        sa.CheckConstraint(
            "status IN ('PENDING', 'APPROVED', 'REJECTED', 'CANCELLED')",
            name=op.f("ck_leave_requests_leave_status"),
        ),
        sa.CheckConstraint(
            "end_date >= start_date", name=op.f("ck_leave_requests_leave_date_range")
        ),
        sa.CheckConstraint(
            "number_of_days > 0", name=op.f("ck_leave_requests_leave_days_positive")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.id"],
            name=op.f("fk_leave_requests_employee_id_users"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["reviewed_by"],
            ["users.id"],
            name=op.f("fk_leave_requests_reviewed_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_leave_requests")),
    )
    with op.batch_alter_table("leave_requests", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_leave_requests_employee_id"), ["employee_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_leave_requests_end_date"), ["end_date"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_leave_requests_reviewed_by"), ["reviewed_by"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_leave_requests_start_date"), ["start_date"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_leave_requests_status"), ["status"], unique=False)

    op.create_table(
        "notifications",
        sa.Column("recipient_id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("notification_type", sa.String(length=32), nullable=False),
        sa.Column("is_read", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.ForeignKeyConstraint(
            ["recipient_id"],
            ["users.id"],
            name=op.f("fk_notifications_recipient_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_notifications")),
    )
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_notifications_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_notifications_is_read"), ["is_read"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_notifications_notification_type"), ["notification_type"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_notifications_recipient_id"), ["recipient_id"], unique=False
        )

    op.create_table(
        "payroll_records",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("effective_from", sa.Date(), nullable=False),
        sa.Column("basic_salary", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("allowances", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("deductions", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("gross_salary", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("net_salary", sa.Numeric(precision=14, scale=2), nullable=False),
        sa.Column("currency", sa.String(length=3), nullable=False),
        sa.Column("payslip_url", sa.String(length=2048), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "allowances >= 0", name=op.f("ck_payroll_records_allowances_non_negative")
        ),
        sa.CheckConstraint(
            "basic_salary >= 0", name=op.f("ck_payroll_records_basic_salary_non_negative")
        ),
        sa.CheckConstraint(
            "deductions >= 0", name=op.f("ck_payroll_records_deductions_non_negative")
        ),
        sa.CheckConstraint(
            "gross_salary >= 0", name=op.f("ck_payroll_records_gross_salary_non_negative")
        ),
        sa.CheckConstraint(
            "net_salary >= 0", name=op.f("ck_payroll_records_net_salary_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.id"],
            name=op.f("fk_payroll_records_employee_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_payroll_records")),
        sa.UniqueConstraint(
            "employee_id", "effective_from", name=op.f("uq_payroll_records_employee_id")
        ),
    )
    with op.batch_alter_table("payroll_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_payroll_records_effective_from"), ["effective_from"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_payroll_records_employee_id"), ["employee_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("payroll_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_payroll_records_employee_id"))
        batch_op.drop_index(batch_op.f("ix_payroll_records_effective_from"))

    op.drop_table("payroll_records")
    with op.batch_alter_table("notifications", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_notifications_recipient_id"))
        batch_op.drop_index(batch_op.f("ix_notifications_notification_type"))
        batch_op.drop_index(batch_op.f("ix_notifications_is_read"))
        batch_op.drop_index(batch_op.f("ix_notifications_created_at"))

    op.drop_table("notifications")
    with op.batch_alter_table("leave_requests", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_leave_requests_status"))
        batch_op.drop_index(batch_op.f("ix_leave_requests_start_date"))
        batch_op.drop_index(batch_op.f("ix_leave_requests_reviewed_by"))
        batch_op.drop_index(batch_op.f("ix_leave_requests_end_date"))
        batch_op.drop_index(batch_op.f("ix_leave_requests_employee_id"))

    op.drop_table("leave_requests")
    with op.batch_alter_table("audit_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_audit_logs_entity_type"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_entity_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_created_at"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_actor_id"))
        batch_op.drop_index(batch_op.f("ix_audit_logs_action"))

    op.drop_table("audit_logs")
    # ### end Alembic commands ###
