"""create attendance records

Revision ID: d30018a7321b
Revises: 93972583a7c4
Create Date: 2026-08-22 13:44:23.205744
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "d30018a7321b"
down_revision: str | None = "93972583a7c4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "attendance_records",
        sa.Column("employee_id", sa.Uuid(), nullable=False),
        sa.Column("attendance_date", sa.Date(), nullable=False),
        sa.Column("check_in_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column("check_out_time", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PRESENT",
                "ABSENT",
                "HALF_DAY",
                "LEAVE",
                name="attendancestatus",
                native_enum=False,
                length=16,
            ),
            nullable=False,
        ),
        sa.Column("work_duration", sa.Integer(), nullable=False),
        sa.Column("remarks", sa.String(length=1000), nullable=True),
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("(CURRENT_TIMESTAMP)"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "status IN ('PRESENT', 'ABSENT', 'HALF_DAY', 'LEAVE')",
            name=op.f("ck_attendance_records_attendance_status"),
        ),
        sa.CheckConstraint(
            "check_out_time IS NULL OR check_in_time IS NOT NULL",
            name=op.f("ck_attendance_records_checkout_requires_checkin"),
        ),
        sa.CheckConstraint(
            "work_duration >= 0", name=op.f("ck_attendance_records_work_duration_non_negative")
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.id"],
            name=op.f("fk_attendance_records_employee_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_attendance_records")),
        sa.UniqueConstraint(
            "employee_id", "attendance_date", name=op.f("uq_attendance_records_employee_id")
        ),
    )
    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_attendance_records_attendance_date"), ["attendance_date"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_attendance_records_employee_id"), ["employee_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("attendance_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_attendance_records_employee_id"))
        batch_op.drop_index(batch_op.f("ix_attendance_records_attendance_date"))

    op.drop_table("attendance_records")
    # ### end Alembic commands ###
